# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jtippetts/Projects/U3DTerrainEditor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jtippetts/Projects/U3DTerrainEditor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtippetts/Projects/U3DTerrainEditor/CMakeFiles /home/jtippetts/Projects/U3DTerrainEditor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtippetts/Projects/U3DTerrainEditor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TEdit

# Build rule for target.
TEdit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TEdit
.PHONY : TEdit

# fast build rule for target.
TEdit/fast:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/build
.PHONY : TEdit/fast

#=============================================================================
# Target rules for targets named ANL

# Build rule for target.
ANL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ANL
.PHONY : ANL

# fast build rule for target.
ANL/fast:
	$(MAKE) -f ThirdParty/ANL/CMakeFiles/ANL.dir/build.make ThirdParty/ANL/CMakeFiles/ANL.dir/build
.PHONY : ANL/fast

BindTerrainEdit.o: BindTerrainEdit.cpp.o
.PHONY : BindTerrainEdit.o

# target to build an object file
BindTerrainEdit.cpp.o:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/BindTerrainEdit.cpp.o
.PHONY : BindTerrainEdit.cpp.o

BindTerrainEdit.i: BindTerrainEdit.cpp.i
.PHONY : BindTerrainEdit.i

# target to preprocess a source file
BindTerrainEdit.cpp.i:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/BindTerrainEdit.cpp.i
.PHONY : BindTerrainEdit.cpp.i

BindTerrainEdit.s: BindTerrainEdit.cpp.s
.PHONY : BindTerrainEdit.s

# target to generate assembly for a file
BindTerrainEdit.cpp.s:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/BindTerrainEdit.cpp.s
.PHONY : BindTerrainEdit.cpp.s

LoadBindings.o: LoadBindings.cpp.o
.PHONY : LoadBindings.o

# target to build an object file
LoadBindings.cpp.o:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/LoadBindings.cpp.o
.PHONY : LoadBindings.cpp.o

LoadBindings.i: LoadBindings.cpp.i
.PHONY : LoadBindings.i

# target to preprocess a source file
LoadBindings.cpp.i:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/LoadBindings.cpp.i
.PHONY : LoadBindings.cpp.i

LoadBindings.s: LoadBindings.cpp.s
.PHONY : LoadBindings.s

# target to generate assembly for a file
LoadBindings.cpp.s:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/LoadBindings.cpp.s
.PHONY : LoadBindings.cpp.s

RegisterComponents.o: RegisterComponents.cpp.o
.PHONY : RegisterComponents.o

# target to build an object file
RegisterComponents.cpp.o:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/RegisterComponents.cpp.o
.PHONY : RegisterComponents.cpp.o

RegisterComponents.i: RegisterComponents.cpp.i
.PHONY : RegisterComponents.i

# target to preprocess a source file
RegisterComponents.cpp.i:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/RegisterComponents.cpp.i
.PHONY : RegisterComponents.cpp.i

RegisterComponents.s: RegisterComponents.cpp.s
.PHONY : RegisterComponents.s

# target to generate assembly for a file
RegisterComponents.cpp.s:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/RegisterComponents.cpp.s
.PHONY : RegisterComponents.cpp.s

TerrainEdit.o: TerrainEdit.cpp.o
.PHONY : TerrainEdit.o

# target to build an object file
TerrainEdit.cpp.o:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/TerrainEdit.cpp.o
.PHONY : TerrainEdit.cpp.o

TerrainEdit.i: TerrainEdit.cpp.i
.PHONY : TerrainEdit.i

# target to preprocess a source file
TerrainEdit.cpp.i:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/TerrainEdit.cpp.i
.PHONY : TerrainEdit.cpp.i

TerrainEdit.s: TerrainEdit.cpp.s
.PHONY : TerrainEdit.s

# target to generate assembly for a file
TerrainEdit.cpp.s:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/TerrainEdit.cpp.s
.PHONY : TerrainEdit.cpp.s

ThirdParty/ANL/Bindings/bind_anl.o: ThirdParty/ANL/Bindings/bind_anl.cpp.o
.PHONY : ThirdParty/ANL/Bindings/bind_anl.o

# target to build an object file
ThirdParty/ANL/Bindings/bind_anl.cpp.o:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/ThirdParty/ANL/Bindings/bind_anl.cpp.o
.PHONY : ThirdParty/ANL/Bindings/bind_anl.cpp.o

ThirdParty/ANL/Bindings/bind_anl.i: ThirdParty/ANL/Bindings/bind_anl.cpp.i
.PHONY : ThirdParty/ANL/Bindings/bind_anl.i

# target to preprocess a source file
ThirdParty/ANL/Bindings/bind_anl.cpp.i:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/ThirdParty/ANL/Bindings/bind_anl.cpp.i
.PHONY : ThirdParty/ANL/Bindings/bind_anl.cpp.i

ThirdParty/ANL/Bindings/bind_anl.s: ThirdParty/ANL/Bindings/bind_anl.cpp.s
.PHONY : ThirdParty/ANL/Bindings/bind_anl.s

# target to generate assembly for a file
ThirdParty/ANL/Bindings/bind_anl.cpp.s:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/ThirdParty/ANL/Bindings/bind_anl.cpp.s
.PHONY : ThirdParty/ANL/Bindings/bind_anl.cpp.s

Urho3DPlayer.o: Urho3DPlayer.cpp.o
.PHONY : Urho3DPlayer.o

# target to build an object file
Urho3DPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/Urho3DPlayer.cpp.o
.PHONY : Urho3DPlayer.cpp.o

Urho3DPlayer.i: Urho3DPlayer.cpp.i
.PHONY : Urho3DPlayer.i

# target to preprocess a source file
Urho3DPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/Urho3DPlayer.cpp.i
.PHONY : Urho3DPlayer.cpp.i

Urho3DPlayer.s: Urho3DPlayer.cpp.s
.PHONY : Urho3DPlayer.s

# target to generate assembly for a file
Urho3DPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/TEdit.dir/build.make CMakeFiles/TEdit.dir/Urho3DPlayer.cpp.s
.PHONY : Urho3DPlayer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... TEdit"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ANL"
	@echo "... BindTerrainEdit.o"
	@echo "... BindTerrainEdit.i"
	@echo "... BindTerrainEdit.s"
	@echo "... LoadBindings.o"
	@echo "... LoadBindings.i"
	@echo "... LoadBindings.s"
	@echo "... RegisterComponents.o"
	@echo "... RegisterComponents.i"
	@echo "... RegisterComponents.s"
	@echo "... TerrainEdit.o"
	@echo "... TerrainEdit.i"
	@echo "... TerrainEdit.s"
	@echo "... ThirdParty/ANL/Bindings/bind_anl.o"
	@echo "... ThirdParty/ANL/Bindings/bind_anl.i"
	@echo "... ThirdParty/ANL/Bindings/bind_anl.s"
	@echo "... Urho3DPlayer.o"
	@echo "... Urho3DPlayer.i"
	@echo "... Urho3DPlayer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

